<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rocket" failures="7" tests="58" name="runner.LocalRunner" time="3464.599" errors="1" timestamp="2023-09-11T20:25:32 IST" skipped="0">
  <testcase classname="runner.LocalRunner" name="runScenario" time="76.642"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="42.912"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="74.596"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="78.615"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="39.150"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="55.887"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="43.665"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="75.966">
    <failure message="expected [] but found [     ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [     ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.PersonalDetailsStepDefiniton.click_save_and_verify_field_with(PersonalDetailsStepDefiniton.java:108)
at ✽.Click save and Verify "Other ID" field with "     "(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:48)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="42.755"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="42.804"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="77.083"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="39.467"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="41.434"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="46.087"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="47.909"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="54.916"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="39.078"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="38.810"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="76.344">
    <failure message="expected [new@1] but found [   new@1   ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [new@1] but found [   new@1   ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.PersonalDetailsStepDefiniton.click_save_and_verify_field_with(PersonalDetailsStepDefiniton.java:108)
at ✽.Click save and Verify "Other ID" field with "   new@1   "(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:48)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="74.444"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="73.718"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="42.415"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="59.532"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="44.825"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="72.981"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="76.073"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="72.612"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="38.566"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="87.351"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="45.662"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="74.992">
    <failure message="expected [Yagami] but found [   Yagami   ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Yagami] but found [   Yagami   ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.PersonalDetailsStepDefiniton.click_save_and_verify_field_with(PersonalDetailsStepDefiniton.java:108)
at ✽.Click save and Verify "Middle name" field with "   Yagami   "(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:77)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="73.732">
    <failure message="expected [] but found [     ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [     ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.PersonalDetailsStepDefiniton.click_save_and_verify_field_with(PersonalDetailsStepDefiniton.java:108)
at ✽.Click save and Verify "Middle name" field with "     "(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:77)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="203.124">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;(//div[@class=&#039;oxd-table-body&#039;]/div/div/div[2])[last()]&quot;}
  (Session info: headless chrome=116.0.5845.180)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.12.1&#039;, revision: &#039;8e34639b11&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;20.0.2&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [679dff959f7c086b66282efaf9e0c1b8, findElement {using=xpath, value=(//div[@class=&#039;oxd-table-body&#039;]/div/div/div[2])[last()]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 116.0.5845.180, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: C:\Users\Ranjith\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:4815}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:4815/devtool..., se:cdpVersion: 116.0.5845.180, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 679dff959f7c086b66282efaf9e0c1b8" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"(//div[@class='oxd-table-body']/div/div/div[2])[last()]"}
  (Session info: headless chrome=116.0.5845.180)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [679dff959f7c086b66282efaf9e0c1b8, findElement {using=xpath, value=(//div[@class='oxd-table-body']/div/div/div[2])[last()]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 116.0.5845.180, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: C:\Users\Ranjith\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:4815}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:4815/devtool..., se:cdpVersion: 116.0.5845.180, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 679dff959f7c086b66282efaf9e0c1b8
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
at pageObjects.PersonalDetails.attachementVerifier(PersonalDetails.java:405)
at stepdefinitions.PersonalDetailsStepDefiniton.verify_the_file_size_as(PersonalDetailsStepDefiniton.java:255)
at ✽.Verify the "maximum_size.jpg" file size "Without Comment" as ""(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:224)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="40.121"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="41.300"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="46.055"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="50.921"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="73.395"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="14.271"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="51.710"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="53.460"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="41.050"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="40.902"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="42.330"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="71.275">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at stepdefinitions.LoginStepDefinition.the_user_is_logged_in(LoginStepDefinition.java:55)
at ✽.The User is logged in(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/Login.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="38.534"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="41.145"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="75.809"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="72.461"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="73.848"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="44.596"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="28.537"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="47.354"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="37.704"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="89.201">
    <failure message="expected [Rei] but found [   Rei   ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Rei] but found [   Rei   ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.PersonalDetailsStepDefiniton.click_save_and_verify_field_with(PersonalDetailsStepDefiniton.java:108)
at ✽.Click save and Verify "First name" field with "   Rei   "(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.LocalRunner" name="runScenario" time="109.422"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="87.973"/>
  <testcase classname="runner.LocalRunner" name="runScenario" time="77.078">
    <failure message="expected [Penber] but found [   Penber   ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Penber] but found [   Penber   ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.PersonalDetailsStepDefiniton.click_save_and_verify_field_with(PersonalDetailsStepDefiniton.java:108)
at ✽.Click save and Verify "Last name" field with "   Penber   "(file:///F:/Learning_Projects/eclipse-space/bdd-OrangeHrm/src/test/resources/Features/PersonalDetails.feature:106)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.LocalRunner -->
